default: &default
  adapter: postgresql
  encoding: unicode
  database: <%= "alex_#{ENV['RAILS_ENV'] || 'development'}" %>
  user: <%= ENV.fetch("POSTGRES_USER") { '' } %>
  password: <%= ENV.fetch("POSTGRES_PASSWORD") { '' } %>
  port: <%= ENV['POSTGRES_PORT'] || 5432 %>
  host: <%= ENV['POSTGRES_HOST'] || 'localhost' %>
  pool: <%= ( ENV.fetch("RAILS_MAX_THREADS") { 2 } ).to_i + 2 %>
  min_messages: DEBUG

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
  min_messages: ERROR
